// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://attrxhhzirlpasubnint.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0dHJ4aGh6aXJscGFzdWJuaW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzNDM4MTUsImV4cCI6MjA0ODkxOTgxNX0.o7kI3zOAZDnFIW9r1VbVYndlI69fq-D8yX4QCZrpcvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);